### ISSUE TITLE
Notification sounds, vibrate and/or LED indicator not working

### ISSUE THREAD

**Issue by mjnewton** [k9mail/k-9#5458]
**Describe the bug**
The arrival of new mail doesn't result in an audible notification, vibration or LED indication despite being set to do so.

**To Reproduce**
1. Ensure relevant notification settings are set in Settings > <Account> > Notifications
2. Ensure that you are not within the Quiet Time set in Settings > General Settings > Notifications (or disable that feature if you are).
3. Ensure phone volumes not set to zero.
4. Send an email to a K-9 configured mailbox and await delivery.
5. Observe arrival of message in status (indicated by envelope) but no accompanying sound, vibration or LED indicator.

**Expected behavior**
Sound, vibration and/or LED indicator accompaniment to the status bar indication, in accordance with the configured settings.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - K-9 Mail version: 5.800
 - Android version: 7.0
 - Device: Samsung Galaxy S6
 - Account type: IMAP with Inbox set for Push

**Additional context**
I originally suspected this to be an instantiation of #5245 but that report explicitly mentions vibrate and LED notifications are working.

**Logs**
I don't currently have the means to access debug logs, sorry.

**Comment by mjnewton** [comment]
Monitoring this a bit more closely I can confirm that *sometimes* the audible/vibratory notifications work but I can't work out the pattern. Most of the time they don't.

I've now been able to obtain a debug log for when a new message coming in, and here's the output (I've removed massively-repetitive entries to shrink it down somewhat):

07-28 11:15:24.021 12024 31515 V RealImapConnection: conn50147518<<<#null# [1452, EXISTS]
07-28 11:15:24.022 12024 31028 V RealImapConnection: conn137252057<<<#null# [1452, EXISTS]
07-28 11:15:24.025 12024 31028 W TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 9: acquired with no timeout.  K-9 Mail should not do this
07-28 11:15:24.025 12024 31515 W TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 10: acquired with no timeout.  K-9 Mail should not do this
07-28 11:15:24.026 12024 31515 V RealImapFolderIdler: ImapFolderIdler[INBOX].idle(): Received a relevant untagged response during IDLE
07-28 11:15:24.030 12024 31028 V RealImapFolderIdler: ImapFolderIdler[INBOX].idle(): Received a relevant untagged response during IDLE
07-28 11:15:24.030 12024 31515 V RealImapConnection: conn50147518>>> DONE
07-28 11:15:24.033 12024 31028 V RealImapConnection: conn137252057>>> DONE
07-28 11:15:24.042 12024 31028 V TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 9: releasing after 17 ms, timeout = null ms
07-28 11:15:24.042 12024 31515 V TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 10: releasing after 17 ms, timeout = null ms
07-28 11:15:24.045 12024 31028 V RealImapConnection: conn137252057<<<#null# [8, RECENT]
07-28 11:15:24.045 12024 31515 V RealImapConnection: conn50147518<<<#null# [8, RECENT]
07-28 11:15:24.048 12024 31028 W TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 9: acquired with no timeout.  K-9 Mail should not do this
07-28 11:15:24.049 12024 31028 V RealImapFolderIdler: ImapFolderIdler[INBOX].idle(): Ignoring untagged response
07-28 11:15:24.050 12024 31515 W TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 10: acquired with no timeout.  K-9 Mail should not do this
07-28 11:15:24.050 12024 31028 V TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 9: releasing after 1 ms, timeout = null ms
07-28 11:15:24.051 12024 31515 V RealImapFolderIdler: ImapFolderIdler[INBOX].idle(): Ignoring untagged response
07-28 11:15:24.052 12024 31515 V TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 10: releasing after 1 ms, timeout = null ms
07-28 11:15:24.053 12024 31028 V RealImapConnection: conn137252057<<<#109# [OK, Idle completed (41.707 + 41.660 + 41.706 secs).]
07-28 11:15:24.054 12024 31515 V RealImapConnection: conn50147518<<<#109# [OK, Idle completed (42.796 + 42.787 + 42.795 secs).]
07-28 11:15:24.055 12024 31028 W TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 9: acquired with no timeout.  K-9 Mail should not do this
07-28 11:15:24.056 12024 31028 V RealImapFolderIdler: ImapFolderIdler[INBOX].idle(): result=SYNC
07-28 11:15:24.056 12024 31515 W TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 10: acquired with no timeout.  K-9 Mail should not do this
07-28 11:15:24.059 12024 12053 I MessagingController: Running command 'synchronizeMailbox', seq = 1286 (background priority)
07-28 11:15:24.060 12024 12053 D MessagingController: Last folder list refresh @ Wed Jul 28 11:02:43 BST 2021. Not refreshing now.
07-28 11:15:24.060 12024 31515 V RealImapFolderIdler: ImapFolderIdler[INBOX].idle(): result=SYNC
07-28 11:15:24.071 12024 12053 I ImapSync: Synchronizing folder NewtonNet:INBOX
07-28 11:15:24.072 12024 12053 V ImapSync: SYNC: About to get local folder INBOX
07-28 11:15:24.077 12024 12053 V ImapSync: SYNC: About to get remote folder INBOX
07-28 11:15:24.078 12024 12053 V ImapSync: SYNC: About to open remote folder INBOX
07-28 11:15:24.080 12024 12053 V RealImapConnection: conn236791679>>> 534 NOOP
07-28 11:15:24.084 12024 12053 V ImapResponseParser: conn236791679<<<#null# [1452, EXISTS]
07-28 11:15:24.084 12024 12053 V ImapResponseParser: conn236791679<<<#null# [8, RECENT]
07-28 11:15:24.085 12024 12053 V ImapResponseParser: conn236791679<<<#534# [OK, NOOP completed (0.001 + 0.000 secs).]
07-28 11:15:24.087 12024 12053 V RealImapConnection: conn236791679>>> 535 EXAMINE "INBOX"
07-28 11:15:24.123 12024 12053 V ImapResponseParser: conn236791679<<<#null# [OK, [CLOSED], Previous mailbox closed.]
07-28 11:15:24.124 12024 12053 V ImapResponseParser: conn236791679<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, $MDNSent, $Forwarded]]
07-28 11:15:24.125 12024 12053 V ImapResponseParser: conn236791679<<<#null# [OK, [PERMANENTFLAGS, []], Read-only mailbox.]
07-28 11:15:24.126 12024 12053 V ImapResponseParser: conn236791679<<<#null# [1452, EXISTS]
07-28 11:15:24.126 12024 12053 V ImapResponseParser: conn236791679<<<#null# [8, RECENT]
07-28 11:15:24.128 12024 12053 V ImapResponseParser: conn236791679<<<#null# [OK, [UNSEEN, 1445], First unseen.]
07-28 11:15:24.128 12024 12053 V ImapResponseParser: conn236791679<<<#null# [OK, [UIDVALIDITY, 1303858022], UIDs valid]
07-28 11:15:24.130 12024 12053 V ImapResponseParser: conn236791679<<<#null# [OK, [UIDNEXT, 121371], Predicted next UID]
07-28 11:15:24.131 12024 12053 V ImapResponseParser: conn236791679<<<#null# [OK, [HIGHESTMODSEQ, 233610], Highest]
07-28 11:15:24.131 12024 12053 V ImapResponseParser: conn236791679<<<#535# [OK, [READ-ONLY], Examine completed (0.032 + 0.000 + 0.031 secs).]
07-28 11:15:24.132 12024 12053 D RealImapFolder: Got untagged EXISTS with value 1452 for NewtonNet:INBOX/MessagingController/conn236791679
07-28 11:15:24.134 12024 12053 D RealImapFolder: Got UidNext = 121371 for NewtonNet:INBOX/MessagingController/conn236791679
07-28 11:15:24.149 12024 12053 V ImapSync: SYNC: Remote message count for folder INBOX is 1452
07-28 11:15:24.150 12024 12053 V ImapSync: SYNC: About to get messages 1053 through 1452 for folder INBOX
07-28 11:15:24.152 12024 12053 V RealImapConnection: conn236791679>>> 536 UID SEARCH 1053:1452 NOT DELETED
07-28 11:15:24.166 12024 12053 V ImapResponseParser: conn236791679<<<#null# [SEARCH, 118829, 118832, 118833, 118834, 118835, 118836, 118837, 118839, 118840, 118841, 118855, 118857, 118858, 118864, 118865, 118879, 118888, 118891, 118901, 118902, 118903, 118917, 118921, 118925, 118928, 118955, 118964, 118968, 118975, 118977, 118980, 118986, 118993, 118996, 118997, 118998, 119028, 119029, 119030, 119031, 119035, 119042, 119058, 119070, 119071, 119073, 119080, 119081, 119087, 119088, 119089, 119091, 119093, 119096, 119097, 119102, 119104, 119114, 119121, 119125, 119137, 119140, 119143, 119146, 119156, 119161, 119163, 119166, 119167, 119169, 119174, 119180, 119181, 119183, 119187, 119196, 119203, 119205, 119215, 119220, 119243, 119244, 119259, 119260, 119272, 119279, 119305, 119306, 119325, 119329, 119333, 119334, 119335, 119339, 119344, 119346, 119349, 119350, 119353, 119357, 119359, 119372, 119373, 119379, 119380, 119386, 119387, 119388, 119389, 119393, 119398, 119399, 119407, 119416, 119423, 119437, 119442, 119443, 119550, 119554, 119555, 119568, 119572, 119577, 119578, 119579, 119580, 119581, 119582, 119584, 119595, 119603, 119611, 119612, 119613, 119614, 119617, 119621, 119626, 119627, 119628, 119633, 119634, 119636, 119637, 119660, 119661, 119662, 119664, 119665, 119666, 119678, 119679, 119680, 119681, 119686, 119717, 119723, 119752, 119754, 119762, 119773, 119774, 119779, 119786, 119787, 119788, 119808, 119811, 119815, 119816, 119826, 119827, 119828, 119834, 119838, 119842, 119844, 119845, 119857, 119876, 119877, 119881, 119886, 119887, 119888, 119889, 119897, 119900, 119904, 119905, 119911, 119912, 119925, 119932, 119939, 119941, 119945, 119946, 119948, 119953, 119957, 119958, 119961, 119962, 119963, 119969, 119971, 120059, 120084, 120099, 120105, 120111, 120115, 120118, 120120, 120123, 120124, 120126, 120128, 120131, 120134, 120135, 120139, 120158, 120164, 120177, 120201, 120206, 120294, 120295, 120300, 120306, 120311, 120366, 120439, 120529, 120534, 120535, 120536, 120537, 120538, 120540, 120556, 120559, 120560, 120561, 120564, 120565, 120566, 120571, 120579, 120599, 120600, 120601, 120602, 120604, 120606, 120607, 120608, 120613, 120615, 120625, 120630, 120631, 120632, 120636, 120637, 120648, 120649, 120650, 120651, 120652, 120653, 120654, 120655, 120656, 120657, 120658, 120659, 120663, 120664, 120665, 120666, 120670, 120685, 120686, 120690, 120695, 120701, 120703, 120704, 120726, 120729, 120732, 120733, 120734, 120735, 120736, 120737, 120740, 120741, 120742, 120743, 120744, 120745, 120746, 120764, 120765, 120766, 120768, 120770, 120771, 120775, 120776, 120777, 120788, 120789, 120793, 120800, 120804, 120810, 120817, 120818, 120819, 120827, 120841, 120844, 120852, 120853, 120856, 120858, 120866, 120891, 120895, 120915, 120952, 120969, 120991, 121002, 121004, 121005, 121007, 121054, 121058, 121062, 121069, 121070, 121072, 121073, 121079, 121090, 121091, 121093, 121094, 121095, 121097, 121099, 121103, 121106, 121109, 121113, 121114, 121116, 121132, 121159, 121164, 121165, 121168, 121176, 121179, 121180, 121181, 121187, 121246, 121254, 121258, 121261, 121274, 121275, 121278, 121327, 121335, 121336, 121338, 121339, 121340, 121341, 121342, 121343, 121344, 121362, 121363, 121364, 121365, 121366, 121367, 121368, 121369, 121370]
07-28 11:15:24.167 12024 12053 V ImapResponseParser: conn236791679<<<#536# [OK, Search completed (0.008 + 0.000 + 0.007 secs).]
07-28 11:15:24.172 12024 12053 V ImapSync: SYNC: Got 400 messages for folder INBOX
07-28 11:15:24.209 12024 12053 V LockableDatabase: LockableDatabase: Transaction ended, took 17 ms / com.fsck.k9.storage.messages.DeleteMessageOperations.destroyMessage(DeleteMessageOperations.kt:20)
07-28 11:15:24.227 12024 12053 V RealImapConnection: conn236791679>>> 537 SEARCH 553:1052 NOT DELETED
07-28 11:15:24.239 12024 12053 V ImapResponseParser: conn236791679<<<#null# [SEARCH, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052]
07-28 11:15:24.240 12024 12053 V ImapResponseParser: conn236791679<<<#537# [OK, Search completed (0.006 + 0.000 + 0.005 secs).]
07-28 11:15:24.250 12024 12053 V ImapSync: Message with uid 121370 has not yet been downloaded
07-28 11:15:24.254 12024 12053 V ImapSync: Message with uid 121369 is present in the local store
07-28 11:15:24.259 12024 12053 V ImapSync: Message with uid 121368 is present in the local store
<snip lots more entries like this>
07-28 11:15:24.670 12024 12053 V ImapSync: Message with uid 118833 is present in the local store
07-28 11:15:24.671 12024 12053 V ImapSync: Message with uid 118832 is present in the local store
07-28 11:15:24.672 12024 12053 V ImapSync: Message with uid 118829 is present in the local store
07-28 11:15:24.672 12024 12053 D ImapSync: SYNC: Have 1 unsynced messages
07-28 11:15:24.672 12024 12053 D ImapSync: SYNC: About to fetch 1 unsynced messages for folder INBOX
07-28 11:15:24.673 12024 12053 V RealImapConnection: conn236791679>>> 538 UID FETCH 121370 (UID FLAGS INTERNALDATE RFC822.SIZE BODY.PEEK[HEADER.FIELDS (date subject from content-type to cc reply-to message-id references in-reply-to X-K9mail-Identity)])
07-28 11:15:24.679 12024 12053 V RealImapConnection: conn236791679<<<#null# [1452, FETCH, [UID, 121370, FLAGS, [\Recent], INTERNALDATE, 28-Jul-2021 11:15:21 +0100, RFC822.SIZE, 8391, BODY, [HEADER.FIELDS, [DATE, SUBJECT, FROM, CONTENT-TYPE, TO, CC, REPLY-TO, MESSAGE-ID, REFERENCES, IN-REPLY-TO, X-K9MAIL-IDENTITY]], From: Mathew Newton <Mathew.Newton643@official.mod.uk>
07-28 11:15:24.679 12024 12053 V RealImapConnection: To: "mathew@newtonnet.co.uk" <mathew@newtonnet.co.uk>
07-28 11:15:24.679 12024 12053 V RealImapConnection: Subject: Test6
07-28 11:15:24.679 12024 12053 V RealImapConnection: Date: Wed, 28 Jul 2021 10:15:18 +0000
07-28 11:15:24.679 12024 12053 V RealImapConnection: Message-ID:
07-28 11:15:24.679 12024 12053 V RealImapConnection:  <AM6PR05MB4822A5B99C443CF448EC10F397EA9@AM6PR05MB4822.eurprd05.prod.outlook.com>
07-28 11:15:24.679 12024 12053 V RealImapConnection: Content-Type: text/plain; charset="iso-8859-1"
07-28 11:15:24.679 12024 12053 V RealImapConnection: 
07-28 11:15:24.679 12024 12053 V RealImapConnection: ]]
07-28 11:15:24.681 12024 12053 V RealImapConnection: conn236791679<<<#538# [OK, Fetch completed (0.003 + 0.000 + 0.002 secs).]
07-28 11:15:24.681 12024 12053 D ImapSync: SYNC: Synced unsynced messages for folder INBOX
07-28 11:15:24.681 12024 12053 D ImapSync: SYNC: Have 0 large messages and 1 small messages out of 1 unsynced messages
07-28 11:15:24.681 12024 12053 D ImapSync: SYNC: Fetching 1 small messages for folder INBOX
07-28 11:15:24.682 12024 12053 V RealImapConnection: conn236791679>>> 539 UID FETCH 121370 (UID BODY.PEEK[])
07-28 11:15:24.690 12024 12053 V RealImapConnection: conn236791679<<<#null# [1452, FETCH, [UID, 121370, BODY, [], 1]]
07-28 11:15:24.696 12024 12053 D BinaryTempFileBody$BinaryTempFileBodyInputStream: Deleting temporary binary file: body1711396198.tmp
07-28 11:15:24.712 12024 12053 V LockableDatabase: LockableDatabase: Transaction ended, took 12 ms / com.fsck.k9.storage.messages.SaveMessageOperations.saveMessage(SaveMessageOperations.kt:82)
07-28 11:15:24.715 12024 12053 V ImapSync$downloadSmallMessages: About to notify listeners that we got a new small message NewtonNet:INBOX:121370
07-28 11:15:24.719 12024 12053 V MessagingController$ControllerSyncListener: Creating notification for message INBOX:121370
07-28 11:15:24.762 12024 12053 V RealImapConnection: conn236791679<<<#539# [OK, Fetch completed (0.004 + 0.000 + 0.003 secs).]
07-28 11:15:24.763 12024 12053 D ImapSync: SYNC: Done fetching small messages for folder INBOX
07-28 11:15:24.763 12024 12053 D ImapSync: SYNC: Fetching large messages for folder INBOX
07-28 11:15:24.763 12024 12053 D ImapSync: SYNC: Done fetching large messages for folder INBOX
07-28 11:15:24.763 12024 12053 D ImapSync: SYNC: About to sync flags for 399 remote messages for folder INBOX
07-28 11:15:24.764 12024 12053 V RealImapConnection: conn236791679>>> 540 UID FETCH 121369,121368,121367,121366,121365,121364,121363,121362,121344,121343,121342,121341,121340,121339,121338,121336,121335,121327,121278,121275,121274,121261,121258,121254,121246,121187,121181,121180,121179,121176,121168,121165,121164,121159,121132,121116,121114,121113,121109,121106,121103,121099,121097,121095,121094,121093,121091,121090,121079,121073,121072,121070,121069,121062,121058,121054,121007,121005,121004,121002,120991,120969,120952,120915,120895,120891,120866,120858,120856,120853,120852,120844,120841,120827,120819,120818,120817,120810,120804,120800,120793,120789,120788,120777,120776,120775,120771,120770,120768,120766,120765,120764,120746,120745,120744,120743,120742,120741,120740,120737 (UID FLAGS)
07-28 11:15:24.769 12024 12053 V RealImapConnection: conn236791679<<<#null# [1352, FETCH, [UID, 120737, FLAGS, [\Seen]]]
07-28 11:15:24.770 12024 12053 V RealImapConnection: conn236791679<<<#null# [1353, FETCH, [UID, 120740, FLAGS, [\Seen]]]
07-28 11:15:24.770 12024 12053 V RealImapConnection: conn236791679<<<#null# [1354, FETCH, [UID, 120741, FLAGS, [\Answered, \Seen]]]
07-28 11:15:24.770 12024 12053 V RealImapConnection: conn236791679<<<#null# [1355, FETCH, [UID, 120742, FLAGS, [\Answered, \Seen]]]
07-28 11:15:24.770 12024 12053 V RealImapConnection: conn236791679<<<#null# [1356, FETCH, [UID, 120743, FLAGS, [\Answered, \Seen]]]
07-28 11:15:24.771 12024 12053 V RealImapConnection: conn236791679<<<#null# [1357, FETCH, [UID, 120744, FLAGS, [\Seen]]]
07-28 11:15:24.771 12024 12053 V RealImapConnection: conn236791679<<<#null# [1358, FETCH, [UID, 120745, FLAGS, [\Seen]]]
07-28 11:15:24.771 12024 12053 V RealImapConnection: conn236791679<<<#null# [1359, FETCH, [UID, 120746, FLAGS, [\Answered, \Seen]]]
07-28 11:15:24.772 12024 12053 V RealImapConnection: conn236791679<<<#null# [1360, FETCH, [UID, 120764, FLAGS, [\Seen]]]
07-28 11:15:24.772 12024 12053 V RealImapConnection: conn236791679<<<#null# [1361, FETCH, [UID, 120765, FLAGS, [\Seen]]]
07-28 11:15:24.772 12024 12053 V RealImapConnection: conn236791679<<<#null# [1362, FETCH, [UID, 120766, FLAGS, [\Seen]]]
<snip lots more entries like this>
07-28 11:15:24.787 12024 12053 V RealImapConnection: conn236791679<<<#null# [1440, FETCH, [UID, 121341, FLAGS, [\Seen]]]
07-28 11:15:24.787 12024 12053 V RealImapConnection: conn236791679<<<#null# [1441, FETCH, [UID, 121342, FLAGS, [\Seen]]]
07-28 11:15:24.788 12024 12053 V RealImapConnection: conn236791679<<<#null# [1442, FETCH, [UID, 121343, FLAGS, [\Seen]]]
07-28 11:15:24.788 12024 12053 V RealImapConnection: conn236791679<<<#null# [1443, FETCH, [UID, 121344, FLAGS, [\Seen]]]
07-28 11:15:24.788 12024 12053 V RealImapConnection: conn236791679<<<#null# [1444, FETCH, [UID, 121362, FLAGS, [\Seen]]]
07-28 11:15:24.788 12024 12053 V RealImapConnection: conn236791679<<<#null# [1445, FETCH, [UID, 121363, FLAGS, [\Recent]]]
07-28 11:15:24.788 12024 12053 V RealImapConnection: conn236791679<<<#null# [1446, FETCH, [UID, 121364, FLAGS, [\Recent]]]
07-28 11:15:24.788 12024 12053 V RealImapConnection: conn236791679<<<#null# [1447, FETCH, [UID, 121365, FLAGS, [\Recent]]]
07-28 11:15:24.789 12024 12053 V RealImapConnection: conn236791679<<<#null# [1448, FETCH, [UID, 121366, FLAGS, [\Recent]]]
07-28 11:15:24.789 12024 12053 V RealImapConnection: conn236791679<<<#null# [1449, FETCH, [UID, 121367, FLAGS, [\Recent]]]
07-28 11:15:24.789 12024 12053 V RealImapConnection: conn236791679<<<#null# [1450, FETCH, [UID, 121368, FLAGS, [\Recent]]]
07-28 11:15:24.789 12024 12053 V RealImapConnection: conn236791679<<<#null# [1451, FETCH, [UID, 121369, FLAGS, [\Recent]]]
07-28 11:15:24.790 12024 12053 V RealImapConnection: conn236791679<<<#540# [OK, Fetch completed (0.005 + 0.001 + 0.004 secs).]
07-28 11:15:24.790 12024 12053 V RealImapConnection: conn236791679>>> 541 UID FETCH 120736,120735,120734,120733,120732,120729,120726,120704,120703,120701,120695,120690,120686,120685,120670,120666,120665,120664,120663,120659,120658,120657,120656,120655,120654,120653,120652,120651,120650,120649,120648,120637,120636,120632,120631,120630,120625,120615,120613,120608,120607,120606,120604,120602,120601,120600,120599,120579,120571,120566,120565,120564,120561,120560,120559,120556,120540,120538,120537,120536,120535,120534,120529,120439,120366,120311,120306,120300,120295,120294,120206,120201,120177,120164,120158,120139,120135,120134,120131,120128,120126,120124,120123,120120,120118,120115,120111,120105,120099,120084,120059,119971,119969,119963,119962,119961,119958,119957,119953,119948 (UID FLAGS)
07-28 11:15:24.798 12024 12053 V RealImapConnection: conn236791679<<<#null# [1252, FETCH, [UID, 119948, FLAGS, [\Seen]]]
07-28 11:15:24.798 12024 12053 V RealImapConnection: conn236791679<<<#null# [1253, FETCH, [UID, 119953, FLAGS, [\Seen]]]
07-28 11:15:24.798 12024 12053 V RealImapConnection: conn236791679<<<#null# [1254, FETCH, [UID, 119957, FLAGS, [\Seen]]]
07-28 11:15:24.799 12024 12053 V RealImapConnection: conn236791679<<<#null# [1255, FETCH, [UID, 119958, FLAGS, [\Seen]]]
07-28 11:15:24.799 12024 12053 V RealImapConnection: conn236791679<<<#null# [1256, FETCH, [UID, 119961, FLAGS, [\Seen]]]
07-28 11:15:24.799 12024 12053 V RealImapConnection: conn236791679<<<#null# [1257, FETCH, [UID, 119962, FLAGS, [\Seen]]]
<snip lots more entries like this>
07-28 11:15:24.843 12024 12053 V RealImapConnection: conn236791679<<<#null# [1250, FETCH, [UID, 119945, FLAGS, [\Seen]]]
07-28 11:15:24.844 12024 12053 V RealImapConnection: conn236791679<<<#null# [1251, FETCH, [UID, 119946, FLAGS, [\Seen]]]
07-28 11:15:24.844 12024 12053 V RealImapConnection: conn236791679<<<#542# [OK, Fetch completed (0.004 + 0.000 + 0.003 secs).]
07-28 11:15:24.845 12024 12053 V RealImapConnection: conn236791679>>> 543 UID FETCH 119353,119350,119349,119346,119344,119339,119335,119334,119333,119329,119325,119306,119305,119279,119272,119260,119259,119244,119243,119220,119215,119205,119203,119196,119187,119183,119181,119180,119174,119169,119167,119166,119163,119161,119156,119146,119143,119140,119137,119125,119121,119114,119104,119102,119097,119096,119093,119091,119089,119088,119087,119081,119080,119073,119071,119070,119058,119042,119035,119031,119030,119029,119028,118998,118997,118996,118993,118986,118980,118977,118975,118968,118964,118955,118928,118925,118921,118917,118903,118902,118901,118891,118888,118879,118865,118864,118858,118857,118855,118841,118840,118839,118837,118836,118835,118834,118833,118832,118829 (UID FLAGS)
07-28 11:15:24.850 12024 12053 V RealImapConnection: conn236791679<<<#null# [1053, FETCH, [UID, 118829, FLAGS, [\Seen]]]
07-28 11:15:24.850 12024 12053 V RealImapConnection: conn236791679<<<#null# [1054, FETCH, [UID, 118832, FLAGS, [\Seen]]]
<snip lots more entries like this>
07-28 11:15:24.873 12024 12053 V RealImapConnection: conn236791679<<<#null# [1150, FETCH, [UID, 119350, FLAGS, [\Seen]]]
07-28 11:15:24.873 12024 12053 V RealImapConnection: conn236791679<<<#null# [1151, FETCH, [UID, 119353, FLAGS, [\Seen]]]
07-28 11:15:24.873 12024 12053 V RealImapConnection: conn236791679<<<#543# [OK, Fetch completed (0.004 + 0.000 + 0.003 secs).]
07-28 11:15:25.176 12024 12053 D ImapSync: SYNC: Synced remote messages for folder INBOX, 1 new messages
07-28 11:15:25.187 12024 12053 D ImapSync: Done synchronizing folder NewtonNet:INBOX @ Wed Jul 28 11:15:25 BST 2021 with 1 new messages
07-28 11:15:25.188 12024 12053 I ImapSync: Done synchronizing folder NewtonNet:INBOX
07-28 11:15:25.188 12024 12053 I MessagingController:  Command 'synchronizeMailbox' completed
07-28 11:15:25.188 12024 12053 I MessagingController: Running command 'synchronizeMailbox', seq = 1287 (background priority)
07-28 11:15:25.189 12024 12053 D MessagingController: Last folder list refresh @ Wed Jul 28 11:02:43 BST 2021. Not refreshing now.
07-28 11:15:25.189 12024 31028 V RealImapFolderIdler: ImapFolderIdler[INBOX].idle()
07-28 11:15:25.190 12024 31028 V RealImapConnection: conn32723537>>> 1253 NOOP
07-28 11:15:25.193 12024 12053 I ImapSync: Synchronizing folder NewtonNet:INBOX
07-28 11:15:25.193 12024 12053 V ImapSync: SYNC: About to get local folder INBOX
07-28 11:15:25.195 12024 12053 V ImapSync: SYNC: About to get remote folder INBOX
07-28 11:15:25.195 12024 12053 V ImapSync: SYNC: About to open remote folder INBOX
07-28 11:15:25.195 12024 12053 V RealImapConnection: conn137252057>>> 110 NOOP
07-28 11:15:25.201 12024 31028 V ImapResponseParser: conn32723537<<<#null# [1452, EXISTS]
07-28 11:15:25.201 12024 31028 V ImapResponseParser: conn32723537<<<#null# [8, RECENT]
07-28 11:15:25.202 12024 31028 V ImapResponseParser: conn32723537<<<#1253# [OK, NOOP completed (0.010 + 0.000 + 0.009 secs).]
07-28 11:15:25.202 12024 31028 V RealImapConnection: conn32723537>>> 1254 EXAMINE "INBOX"
07-28 11:15:25.209 12024 12053 V ImapResponseParser: conn137252057<<<#110# [OK, NOOP completed (0.011 + 0.000 + 0.010 secs).]
07-28 11:15:25.210 12024 12053 V RealImapConnection: conn137252057>>> 111 EXAMINE "INBOX"
07-28 11:15:25.230 12024 31028 V ImapResponseParser: conn32723537<<<#null# [OK, [CLOSED], Previous mailbox closed.]
07-28 11:15:25.230 12024 31028 V ImapResponseParser: conn32723537<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, $MDNSent, $Forwarded]]
07-28 11:15:25.231 12024 31028 V ImapResponseParser: conn32723537<<<#null# [OK, [PERMANENTFLAGS, []], Read-only mailbox.]
07-28 11:15:25.231 12024 31028 V ImapResponseParser: conn32723537<<<#null# [1452, EXISTS]
07-28 11:15:25.231 12024 31028 V ImapResponseParser: conn32723537<<<#null# [8, RECENT]
07-28 11:15:25.232 12024 31028 V ImapResponseParser: conn32723537<<<#null# [OK, [UNSEEN, 1445], First unseen.]
07-28 11:15:25.232 12024 31028 V ImapResponseParser: conn32723537<<<#null# [OK, [UIDVALIDITY, 1303858022], UIDs valid]
07-28 11:15:25.232 12024 31028 V ImapResponseParser: conn32723537<<<#null# [OK, [UIDNEXT, 121371], Predicted next UID]
07-28 11:15:25.232 12024 31028 V ImapResponseParser: conn32723537<<<#null# [OK, [HIGHESTMODSEQ, 233610], Highest]
07-28 11:15:25.233 12024 31028 V ImapResponseParser: conn32723537<<<#1254# [OK, [READ-ONLY], Examine completed (0.024 + 0.000 + 0.023 secs).]
07-28 11:15:25.233 12024 31028 D RealImapFolder: Got untagged EXISTS with value 1452 for NewtonNet:INBOX/ImapFolderPusher-NewtonNet-INBOX/conn32723537
07-28 11:15:25.233 12024 31028 D RealImapFolder: Got UidNext = 121371 for NewtonNet:INBOX/ImapFolderPusher-NewtonNet-INBOX/conn32723537
07-28 11:15:25.234 12024 31028 V RealImapConnection: Connection conn32723537 has 34 capabilities
07-28 11:15:25.234 12024 31028 V RealImapConnection: conn32723537>>> 1255 IDLE
07-28 11:15:25.239 12024 31028 V RealImapConnection: conn32723537<<<#+# [idling]
07-28 11:15:25.242 12024 12053 V ImapResponseParser: conn137252057<<<#null# [OK, [CLOSED], Previous mailbox closed.]
07-28 11:15:25.243 12024 12053 V ImapResponseParser: conn137252057<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, $MDNSent, $Forwarded]]
07-28 11:15:25.243 12024 12053 V ImapResponseParser: conn137252057<<<#null# [OK, [PERMANENTFLAGS, []], Read-only mailbox.]
07-28 11:15:25.243 12024 31028 V TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 9: releasing after 1188 ms, timeout = null ms
07-28 11:15:25.243 12024 12053 V ImapResponseParser: conn137252057<<<#null# [1452, EXISTS]
07-28 11:15:25.244 12024 12053 V ImapResponseParser: conn137252057<<<#null# [8, RECENT]
07-28 11:15:25.244 12024 12053 V ImapResponseParser: conn137252057<<<#null# [OK, [UNSEEN, 1445], First unseen.]
07-28 11:15:25.244 12024 12053 V ImapResponseParser: conn137252057<<<#null# [OK, [UIDVALIDITY, 1303858022], UIDs valid]
07-28 11:15:25.245 12024 12053 V ImapResponseParser: conn137252057<<<#null# [OK, [UIDNEXT, 121371], Predicted next UID]
07-28 11:15:25.245 12024 12053 V ImapResponseParser: conn137252057<<<#null# [OK, [HIGHESTMODSEQ, 233610], Highest]
07-28 11:15:25.245 12024 12053 V ImapResponseParser: conn137252057<<<#111# [OK, [READ-ONLY], Examine completed (0.029 + 0.000 + 0.028 secs).]
07-28 11:15:25.246 12024 12053 D RealImapFolder: Got untagged EXISTS with value 1452 for NewtonNet:INBOX/MessagingController/conn137252057
07-28 11:15:25.246 12024 12053 D RealImapFolder: Got UidNext = 121371 for NewtonNet:INBOX/MessagingController/conn137252057
07-28 11:15:25.256 12024 12053 V ImapSync: SYNC: Remote message count for folder INBOX is 1452
07-28 11:15:25.256 12024 12053 V ImapSync: SYNC: About to get messages 1053 through 1452 for folder INBOX
07-28 11:15:25.257 12024 12053 V RealImapConnection: conn137252057>>> 112 UID SEARCH 1053:1452 NOT DELETED
07-28 11:15:25.272 12024 12053 V ImapResponseParser: conn137252057<<<#null# [SEARCH, 118829, 118832, 118833, 118834, 118835, 118836, 118837, 118839, 118840, 118841, 118855, 118857, 118858, 118864, 118865, 118879, 118888, 118891, 118901, 118902, 118903, 118917, 118921, 118925, 118928, 118955, 118964, 118968, 118975, 118977, 118980, 118986, 118993, 118996, 118997, 118998, 119028, 119029, 119030, 119031, 119035, 119042, 119058, 119070, 119071, 119073, 119080, 119081, 119087, 119088, 119089, 119091, 119093, 119096, 119097, 119102, 119104, 119114, 119121, 119125, 119137, 119140, 119143, 119146, 119156, 119161, 119163, 119166, 119167, 119169, 119174, 119180, 119181, 119183, 119187, 119196, 119203, 119205, 119215, 119220, 119243, 119244, 119259, 119260, 119272, 119279, 119305, 119306, 119325, 119329, 119333, 119334, 119335, 119339, 119344, 119346, 119349, 119350, 119353, 119357, 119359, 119372, 119373, 119379, 119380, 119386, 119387, 119388, 119389, 119393, 119398, 119399, 119407, 119416, 119423, 119437, 119442, 119443, 119550, 119554, 119555, 119568, 119572, 119577, 119578, 119579, 119580, 119581, 119582, 119584, 119595, 119603, 119611, 119612, 119613, 119614, 119617, 119621, 119626, 119627, 119628, 119633, 119634, 119636, 119637, 119660, 119661, 119662, 119664, 119665, 119666, 119678, 119679, 119680, 119681, 119686, 119717, 119723, 119752, 119754, 119762, 119773, 119774, 119779, 119786, 119787, 119788, 119808, 119811, 119815, 119816, 119826, 119827, 119828, 119834, 119838, 119842, 119844, 119845, 119857, 119876, 119877, 119881, 119886, 119887, 119888, 119889, 119897, 119900, 119904, 119905, 119911, 119912, 119925, 119932, 119939, 119941, 119945, 119946, 119948, 119953, 119957, 119958, 119961, 119962, 119963, 119969, 119971, 120059, 120084, 120099, 120105, 120111, 120115, 120118, 120120, 120123, 120124, 120126, 120128, 120131, 120134, 120135, 120139, 120158, 120164, 120177, 120201, 120206, 120294, 120295, 120300, 120306, 120311, 120366, 120439, 120529, 120534, 120535, 120536, 120537, 120538, 120540, 120556, 120559, 120560, 120561, 120564, 120565, 120566, 120571, 120579, 120599, 120600, 120601, 120602, 120604, 120606, 120607, 120608, 120613, 120615, 120625, 120630, 120631, 120632, 120636, 120637, 120648, 120649, 120650, 120651, 120652, 120653, 120654, 120655, 120656, 120657, 120658, 120659, 120663, 120664, 120665, 120666, 120670, 120685, 120686, 120690, 120695, 120701, 120703, 120704, 120726, 120729, 120732, 120733, 120734, 120735, 120736, 120737, 120740, 120741, 120742, 120743, 120744, 120745, 120746, 120764, 120765, 120766, 120768, 120770, 120771, 120775, 120776, 120777, 120788, 120789, 120793, 120800, 120804, 120810, 120817, 120818, 120819, 120827, 120841, 120844, 120852, 120853, 120856, 120858, 120866, 120891, 120895, 120915, 120952, 120969, 120991, 121002, 121004, 121005, 121007, 121054, 121058, 121062, 121069, 121070, 121072, 121073, 121079, 121090, 121091, 121093, 121094, 121095, 121097, 121099, 121103, 121106, 121109, 121113, 121114, 121116, 121132, 121159, 121164, 121165, 121168, 121176, 121179, 121180, 121181, 121187, 121246, 121254, 121258, 121261, 121274, 121275, 121278, 121327, 121335, 121336, 121338, 121339, 121340, 121341, 121342, 121343, 121344, 121362, 121363, 121364, 121365, 121366, 121367, 121368, 121369, 121370]
07-28 11:15:25.272 12024 12053 V ImapResponseParser: conn137252057<<<#112# [OK, Search completed (0.005 + 0.000 + 0.004 secs).]
07-28 11:15:25.277 12024 12053 V ImapSync: SYNC: Got 400 messages for folder INBOX
07-28 11:15:25.280 12024 12053 V ImapSync: Message with uid 121370 is present in the local store
07-28 11:15:25.282 12024 12053 V ImapSync: Message with uid 121369 is present in the local store
<snip lots more entries like this>
07-28 11:15:25.762 12024 12053 V ImapSync: Message with uid 118832 is present in the local store
07-28 11:15:25.763 12024 12053 V ImapSync: Message with uid 118829 is present in the local store
07-28 11:15:25.764 12024 12053 D ImapSync: SYNC: Have 0 unsynced messages
07-28 11:15:25.764 12024 12053 D ImapSync: SYNC: Have 0 large messages and 0 small messages out of 0 unsynced messages
07-28 11:15:25.764 12024 12053 D ImapSync: SYNC: Fetching 0 small messages for folder INBOX
07-28 11:15:25.765 12024 12053 D ImapSync: SYNC: Done fetching small messages for folder INBOX
07-28 11:15:25.765 12024 12053 D ImapSync: SYNC: Fetching large messages for folder INBOX
07-28 11:15:25.765 12024 12053 D ImapSync: SYNC: Done fetching large messages for folder INBOX
07-28 11:15:25.765 12024 12053 D ImapSync: SYNC: About to sync flags for 400 remote messages for folder INBOX
07-28 11:15:25.767 12024 12053 V RealImapConnection: conn137252057>>> 113 UID FETCH 121370,121369,121368,121367,121366,121365,121364,121363,121362,121344,121343,121342,121341,121340,121339,121338,121336,121335,121327,121278,121275,121274,121261,121258,121254,121246,121187,121181,121180,121179,121176,121168,121165,121164,121159,121132,121116,121114,121113,121109,121106,121103,121099,121097,121095,121094,121093,121091,121090,121079,121073,121072,121070,121069,121062,121058,121054,121007,121005,121004,121002,120991,120969,120952,120915,120895,120891,120866,120858,120856,120853,120852,120844,120841,120827,120819,120818,120817,120810,120804,120800,120793,120789,120788,120777,120776,120775,120771,120770,120768,120766,120765,120764,120746,120745,120744,120743,120742,120741,120740 (UID FLAGS)
07-28 11:15:25.775 12024 12053 V RealImapConnection: conn137252057<<<#null# [1353, FETCH, [UID, 120740, FLAGS, [\Seen]]]
07-28 11:15:25.776 12024 12053 V RealImapConnection: conn137252057<<<#null# [1354, FETCH, [UID, 120741, FLAGS, [\Answered, \Seen]]]
07-28 11:15:25.776 12024 12053 V RealImapConnection: conn137252057<<<#null# [1355, FETCH, [UID, 120742, FLAGS, [\Answered, \Seen]]]
07-28 11:15:25.776 12024 12053 V RealImapConnection: conn137252057<<<#null# [1356, FETCH, [UID, 120743, FLAGS, [\Answered, \Seen]]]
<snip lots more entries like this>
07-28 11:15:25.971 12024 12053 V RealImapConnection: conn137252057<<<#null# [1150, FETCH, [UID, 119350, FLAGS, [\Seen]]]
07-28 11:15:25.972 12024 12053 V RealImapConnection: conn137252057<<<#null# [1151, FETCH, [UID, 119353, FLAGS, [\Seen]]]
07-28 11:15:25.972 12024 12053 V RealImapConnection: conn137252057<<<#null# [1152, FETCH, [UID, 119357, FLAGS, [\Answered, \Seen]]]
07-28 11:15:25.972 12024 12053 V RealImapConnection: conn137252057<<<#116# [OK, Fetch completed (0.003 + 0.000 + 0.002 secs).]
07-28 11:15:26.371 12024 12053 D ImapSync: SYNC: Synced remote messages for folder INBOX, 0 new messages
07-28 11:15:26.392 12024 12053 D ImapSync: Done synchronizing folder NewtonNet:INBOX @ Wed Jul 28 11:15:26 BST 2021 with 0 new messages
07-28 11:15:26.393 12024 12053 I ImapSync: Done synchronizing folder NewtonNet:INBOX
07-28 11:15:26.393 12024 12053 I MessagingController:  Command 'synchronizeMailbox' completed
07-28 11:15:26.414 12024 31515 V RealImapFolderIdler: ImapFolderIdler[INBOX].idle()
07-28 11:15:26.416 12024 31515 V RealImapConnection: conn50147518>>> 110 NOOP
07-28 11:15:26.420 12024 31515 V ImapResponseParser: conn50147518<<<#110# [OK, NOOP completed (0.001 + 0.000 secs).]
07-28 11:15:26.422 12024 31515 V RealImapConnection: conn50147518>>> 111 EXAMINE "INBOX"
07-28 11:15:26.432 12024 31515 V ImapResponseParser: conn50147518<<<#null# [OK, [CLOSED], Previous mailbox closed.]
07-28 11:15:26.433 12024 31515 V ImapResponseParser: conn50147518<<<#null# [FLAGS, [\Answered, \Flagged, \Deleted, \Seen, \Draft, $MDNSent, $Forwarded]]
07-28 11:15:26.434 12024 31515 V ImapResponseParser: conn50147518<<<#null# [OK, [PERMANENTFLAGS, []], Read-only mailbox.]
07-28 11:15:26.436 12024 31515 V ImapResponseParser: conn50147518<<<#null# [1452, EXISTS]
07-28 11:15:26.437 12024 31515 V ImapResponseParser: conn50147518<<<#null# [8, RECENT]
07-28 11:15:26.438 12024 31515 V ImapResponseParser: conn50147518<<<#null# [OK, [UNSEEN, 1445], First unseen.]
07-28 11:15:26.439 12024 31515 V ImapResponseParser: conn50147518<<<#null# [OK, [UIDVALIDITY, 1303858022], UIDs valid]
07-28 11:15:26.440 12024 31515 V ImapResponseParser: conn50147518<<<#null# [OK, [UIDNEXT, 121371], Predicted next UID]
07-28 11:15:26.472 12024 31515 V ImapResponseParser: conn50147518<<<#null# [OK, [HIGHESTMODSEQ, 233610], Highest]
07-28 11:15:26.473 12024 31515 V ImapResponseParser: conn50147518<<<#111# [OK, [READ-ONLY], Examine completed (0.007 + 0.000 + 0.006 secs).]
07-28 11:15:26.474 12024 31515 D RealImapFolder: Got untagged EXISTS with value 1452 for NewtonNet:INBOX/ImapFolderPusher-NewtonNet-INBOX/conn50147518
07-28 11:15:26.476 12024 31515 D RealImapFolder: Got UidNext = 121371 for NewtonNet:INBOX/ImapFolderPusher-NewtonNet-INBOX/conn50147518
07-28 11:15:26.477 12024 31515 V RealImapConnection: Connection conn50147518 has 34 capabilities
07-28 11:15:26.480 12024 31515 V RealImapConnection: conn50147518>>> 112 IDLE
07-28 11:15:26.481 12024 31515 V RealImapConnection: conn50147518<<<#+# [idling]
07-28 11:15:26.483 12024 31515 V TracingPowerManager$TracingWakeLock: TracingWakeLock for tag ImapFolderPusher-NewtonNet-INBOX / id 10: releasing after 2426 ms, timeout = null ms

**Comment by NickJH** [comment]
As far as I can determine, the notification happens when I delete something on a PC. The PC is using IMAP and and when deleting, it marks the e-mail read (if it is not already) then moves it to the Deleted/Trash folder. If I do an immediate delete (shift and delete in Thunderbird, my desktop client) I do not appear to get a notification (which is great!).

**Comment by cketti** [comment]
I've fixed a couple of notification bugs in K-9 Mail 5.802. https://github.com/k9mail/k-9/releases/tag/5.802

Can you please test if that version fixes your notification issues?

**Comment by mjnewton** [comment]
Yes that seems to have fixed it (for me) - thanks @cketti!

**Comment by alex-taylor** [comment]
But not for me.  I've updated and I still get no notification sounds/vibration.

**Comment by cketti** [comment]
@alex-taylor: Please create a new issue and provide detailed steps on how to reproduce the behavior you're observing. Also make sure sound/vibration isn't disabled in Android's notification settings.
