### ISSUE TITLE
Deleting message(s) from notification unnecessarily unlocks the phone

### ISSUE THREAD

**Issue by mruwek** [k9mail/k-9#638]
I believe the title is pretty self-explanatory, but nonetheless I'll try to describe this issue briefly:

Steps to reproduce:
1. Mail arrives while phone is locked
2. Expand the notification and hit the delete button
3. Message is deleted and phone **is unlocked**

Expected behavior:
Message is deleted and phone remains locked.

**Comment by maniac103** [comment]
I assume this is Lollipop? If yes, I don't think anything can't be done about that: previous Android versions only unlocked the keyguard for activity PendingIntents, L does it fornall of them (activity, broadcast, service).

**Comment by mruwek** [comment]
Deleting messages from notification in Gmail app doesn't unlock the phone, so it's definitely possible. Also marking messages as read in K9 works well. Only deleting causes the problem.

**Comment by cketti** [comment]
This should be fixed in `master`

**Comment by jahabrewer** [comment]
I'm running K9 5.008 from Google Play on Android 6.0.1 and I'm still seeing this issue. I couldn't find the particular commit that fixed this, so I'm not positive that the fix is in this version. But, I only looked briefly and I'm not familiar with this project.

Do I need a fresher version of K9? Or is the fix coming down the release pipeline?

**Comment by cketti** [comment]
It'll be a while until a stable version containing this fix will be released. If you like danger [check back](https://github.com/k9mail/k-9/releases) in a few days when the new alpha v5.108 should be ready.

**Comment by jahabrewer** [comment]
Ah, I see. Thanks for the help.
